name: MLBD-MRes 
channels:
- fastai
- pyg
- pytorch
- conda-forge
- defaults
dependencies:
- pyg
- pytorch-lightning
- fastcore>=1.3.8
- torchvision>=0.8
- matplotlib
- pandas>=1.0.0
- requests
- pyyaml
- fastprogress>=0.2.4
- pillow>=6.0.0
- scikit-learn
- scipy
- spacy
- pytorch>=1.7.0
- julia>=1.6.3
- jupyter
- notebook
- jupyter_contrib_nbextensions

